export const FORM_PROJECT = 'FORM_PROJECT'
export const GET_PROJECTS = 'GET_PROJECTS'
export const ADD_PROJECT = 'ADD_PROJECT'
export const CHECK_PROJECTFORM = 'CHECK_PROJECTFORM'
export const CURRENT_PROJECT = 'CURRENT_PROJECT'
export const EDIT_PROJECT = 'EDIT_PROJECT'
export const DELETE_PROJECT = 'DELETE_PROJECT'
export const ERROR_PROJECT = 'ERROR_PROJECT'

/* export const PROJECT_TASKS = 'PROJECT_TASKS'
export const ADD_TASK = 'ADD_TASK'
export const CHECK_TASKFORM = 'CHECK_TASKFORM'
export const DELETE_TASK = 'DELETE_TASK'
export const CURRENT_TASK = 'CURRENT_TASK'
export const EDIT_TASK = 'EDIT_TASK'
export const ERROR_TASK = 'ERROR_TASK' */

export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'

export const GET_USER = 'GET_USER'
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN'
export const ERROR_LOGIN = 'ERROR_LOGIN'
export const HANDLE_LOGOUT = 'HANDLE_LOGOUT'
